[project]
name = "winkleman"
version = "0.1.0"
description = "A chat client for Claude via Anthropic API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.36.12",
    "pypdf2>=3.0.1",
    "streamlit>=1.41.1",
    "anthropic"
]
